services:
  postgres:
    container_name: postgresdb
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: userdb
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - foundit-network
    restart: unless-stopped

  loginservice:
    build :
      context: .
      dockerfile: Dockerfile    
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/userdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - postgres
    networks:
      - foundit-network
    
networks:
  foundit-network:
    driver: bridge

volumes:
  postgres:
    driver: local